/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmbitieSlugRouteImport } from './routes/ambitie.$slug'
import { Route as DienstSlugRouteImport } from './routes/dienst.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbitieSlugRoute = AmbitieSlugRouteImport.update({
  id: '/ambitie/$slug',
  path: '/ambitie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstSlugRoute = DienstSlugRouteImport.update({
  id: '/dienst/$slug',
  path: '/dienst/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambitie/$slug': typeof AmbitieSlugRoute
  '/dienst/$slug': typeof DienstSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambitie/$slug': typeof AmbitieSlugRoute
  '/dienst/$slug': typeof DienstSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambitie/$slug': typeof AmbitieSlugRoute
  '/dienst/$slug': typeof DienstSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ambitie/$slug' | '/dienst/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ambitie/$slug' | '/dienst/$slug'
  id: '__root__' | '/' | '/ambitie/$slug' | '/dienst/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbitieSlugRoute: typeof AmbitieSlugRoute
  DienstSlugRoute: typeof DienstSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambitie/$slug': {
      id: '/ambitie/$slug'
      path: '/ambitie/$slug'
      fullPath: '/ambitie/$slug'
      preLoaderRoute: typeof AmbitieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dienst/$slug': {
      id: '/dienst/$slug'
      path: '/dienst/$slug'
      fullPath: '/dienst/$slug'
      preLoaderRoute: typeof DienstSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbitieSlugRoute: AmbitieSlugRoute,
  DienstSlugRoute: DienstSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
